name: studymate
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  qr_code_scanner: ^1.0.1
  flutter_rating_bar: ^4.0.1
  qr_flutter: ^4.0.0
  cupertino_icons: ^1.0.2
  english_words: ^4.0.0
  provider: ^6.0.0
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.0
  sliding_switch: ^1.1.0
  badges: ^3.0.2
  shared_preferences: ^2.0.17
  substring_highlight: ^1.0.33
  firebase_auth: ^4.2.4
  firebase_core: ^2.8.0
  firebase_auth_web: ^5.2.10
  cloud_firestore: ^4.3.1
  cloud_firestore_web: ^3.3.5
  email_validator: ^2.1.17
  google_sign_in: ^6.0.1
  file_picker: ^5.2.5
  firebase_storage: ^11.0.10
  intl: ^0.18.0
  table_calendar: ^3.0.8
  image_picker: ^1.0.0
  image_cropper: ^4.0.0
  geolocator: ^9.0.2
  geocoding: ^2.0.4
  google_maps_flutter: ^2.1.7
  http: ^0.13.0
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  permission_handler: ^10.4.2
  search_map_location: 0.0.6
  url_launcher: ^6.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.6


flutter:
  generate: true 
  assets:
    - assets/boarding/
    - assets/login/
    - assets/data.json
  uses-material-design: true

  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"